##
## FZF and Skim theme — generated by Omarchy
##

## FZF
export FZF_DEFAULT_OPTS=" \
--color=bg+:{{ color0 }},bg:{{ background }},spinner:{{ cursor }},hl:{{ color1 }} \
--color=fg:{{ foreground }},header:{{ color1 }},info:{{ color5 }},pointer:{{ cursor }} \
--color=marker:{{ color4 }},fg+:{{ foreground }},prompt:{{ color5 }},hl+:{{ color2 }} \
--color=selected-bg:{{ color2 }} \
--multi"

## Skim / sk
export SKIM_DEFAULT_OPTIONS="$SKIM_DEFAULT_OPTIONS \
--color=fg:{{ foreground }},bg:{{ background }},matched:{{ color0 }},matched_bg:{{ cursor }},current:{{ foreground }},current_bg:{{ color8 }},current_match:{{ background }},current_match_bg:{{ cursor }},spinner:{{ color2 }},info:{{ color5 }},prompt:{{ color4 }},cursor:{{ color1 }},selected:{{ color1 }},header:{{ color6 }},border:{{ color8 }}"
