##
## Gum theme — generated by Omarchy
##

## gum choose
export GUM_CHOOSE_CURSOR_FOREGROUND="{{ cursor }}"
export GUM_CHOOSE_HEADER_FOREGROUND="{{ color4 }}"
export GUM_CHOOSE_ITEM_FOREGROUND="{{ foreground }}"
export GUM_CHOOSE_SELECTED_FOREGROUND="{{ color2 }}"

## gum confirm
export GUM_CONFIRM_PROMPT_FOREGROUND="{{ color4 }}"
export GUM_CONFIRM_SELECTED_FOREGROUND="{{ background }}"
export GUM_CONFIRM_SELECTED_BACKGROUND="{{ accent }}"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="{{ foreground }}"
export GUM_CONFIRM_UNSELECTED_BACKGROUND="{{ color0 }}"

## gum input
export GUM_INPUT_PROMPT_FOREGROUND="{{ color4 }}"
export GUM_INPUT_CURSOR_FOREGROUND="{{ cursor }}"
export GUM_INPUT_PLACEHOLDER_FOREGROUND="{{ color8 }}"
export GUM_INPUT_HEADER_FOREGROUND="{{ color8 }}"
