theme = "custom"
mode = "auto"
vcs = "git"
exclude_untracked = false
line_numbers = true
wrap_lines = false
hunk_headers = true
agent_notes = false

[custom_theme]
base = "graphite"
label = "Omarchy"
background = "#1e1e2e"
panel = "#1e1e2e"
panelAlt = ""
border = ""
accent = "#89b4fa"
accentMuted = ""
text = "#cdd6f4"
muted = ""
addedBg = "#1e1e2e"
removedBg = "#1e1e2e"
contextBg = "#1e1e2e"
addedContentBg = ""
removedContentBg = ""
contextContentBg = "#1e1e2e"
addedSignColor = ""
removedSignColor = ""
lineNumberBg = "#1e1e2e"
lineNumberFg = ""
selectedHunk = ""
badgeAdded = ""
badgeRemoved = ""
badgeNeutral = ""
fileNew = ""
fileDeleted = ""
fileRenamed = ""
fileModified = ""
fileUntracked = ""
noteBorder = ""
noteBackground = "#1e1e2e"
noteTitleBackground = ""
noteTitleText = "#cdd6f4"

[custom_theme.syntax]
default = "#cdd6f4"
keyword = ""
string = ""
comment = ""
number = ""
function = ""
property = ""
type = ""
punctuation = ""
