# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

monitor = desc:Lenovo Group Limited P40WD-40, 5120x2160@120, auto, 2
