# Catppuccin Frappé
foreground              #C6D0F5
background              #303446
selection_foreground    #303446
selection_background    #F2D5CF
cursor                  #F2D5CF
cursor_text_color       #303446
url_color               #85C1DC
active_tab_foreground   #303446
active_tab_background   #CA9EE6
inactive_tab_foreground #C6D0F5
inactive_tab_background #414559
tab_bar_background      #292C3C
color0  #51576D
color1  #E78284
color2  #A6D189
color3  #E5C890
color4  #8CAAEE
color5  #F4B8E4
color6  #81C8BE
color7  #B5BFE2
color8  #626880
color9  #E78284
color10 #A6D189
color11 #E5C890
color12 #8CAAEE
color13 #F4B8E4
color14 #81C8BE
color15 #A5ADCE

# Font
font_family OperatorMono Nerd Font
bold_italic_font auto

# Window
window_padding_width 14
macos_titlebar_color background
hide_window_decorations titlebar-only
confirm_os_window_close 0
include ~/.config/kitty/machine.conf

# Keybindings
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
map shift+return send_text normal \x1b\r
map cmd+enter toggle_fullscreen
map cmd+left previous_tab
map cmd+right next_tab
map ctrl+alt+1 goto_tab 1
map ctrl+alt+2 goto_tab 2
map ctrl+alt+3 goto_tab 3
map ctrl+alt+4 goto_tab 4
map ctrl+alt+5 goto_tab 5
map ctrl+alt+6 goto_tab 6
map ctrl+alt+7 goto_tab 7
map ctrl+alt+8 goto_tab 8
map ctrl+alt+9 goto_tab 9

# Splits (native Kitty leader key)
enabled_layouts splits,tall,fat,grid,horizontal,vertical
map ctrl+k>right launch --location=vsplit --cwd=current
map ctrl+k>left  launch --location=vsplit --cwd=current
map ctrl+k>up    launch --location=hsplit --cwd=current
map ctrl+k>down  launch --location=hsplit --cwd=current
map ctrl+k>shift+right neighboring_window right
map ctrl+k>shift+left  neighboring_window left
map ctrl+k>shift+up    neighboring_window up
map ctrl+k>shift+down  neighboring_window down
map ctrl+k>l neighboring_window right
map ctrl+k>h neighboring_window left
map ctrl+k>k neighboring_window up
map ctrl+k>j neighboring_window down
map ctrl+alt+left  neighboring_window left
map ctrl+alt+right neighboring_window right
map ctrl+alt+up    neighboring_window up
map ctrl+alt+down  neighboring_window down

# Allow remote access
allow_remote_control yes

# Aesthetics
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor
enable_audio_bell no

# Tab bar
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
