# Extra autostart processes
# exec-once = uwsm-app -- my-service

# >>> Neo autostart
# Neo provides the native notification server.
exec-once = pkill mako || true
exec-once = env NEOSH_SOURCE_ROOT=$HOME/src/neosh neosh-restart-quickshell
exec-once = zscaler-tray-after-status-notifier
# <<< Neo autostart
