# Extra autostart processes
# exec-once = uwsm-app -- my-service

exec-once = zscaler-tray-after-status-notifier

# >>> Neo Quickshell autostart
# Quickshell provides Neo's native bar and notification server.
exec-once = /home/douglas/.local/bin/neosh-stop-omarchy-shell; /home/douglas/.local/bin/neosh-restart-quickshell
# <<< Neo Quickshell autostart
