# Gazelle WiFi TUI - floating window
# New Hyprland Syntax using match:initial_class (xdg-terminal-exec and Ghostty friendly)
windowrule = float on, center on, size 800 600, match:initial_class org.omarchy.Gazelle
windowrule = float on, center on, size 600 400, match:initial_class org.omarchy.Calendar
windowrule = float on, center on, size 700 400, match:initial_class org.omarchy.Lcctop
