#!/bin/sh

case ":${PATH}:" in
  *:"$HOME/.cache/.bun/bin":*)
    ;;
  *)
    export PATH="$HOME/.cache/.bun/bin:$PATH"
    ;;
esac

case ":${PATH}:" in
  *:"$HOME/.bin":*)
    ;;
  *)
    export PATH="$HOME/.bin:$PATH"
    ;;
esac
