monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-KEF_LSX_II-01"
      }
    ]
    actions = {
      update-props = {
        api.acp.auto-profile = false
        api.acp.auto-port = true
        device.profile = "pro-audio"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.usb-KEF_LSX_II-01.pro-output-0"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
        api.alsa.headroom = 3072
        audio.rate = 96000
      }
    }
  }
]
