monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.usb-KEF_LSX_II-01.pro-output-0"
      }
    ]
    actions = {
      update-props = {
        api.alsa.headroom = 2048
        audio.rate = 96000
      }
    }
  }
]
