# ZSH Syntax Highlighting Theme — generated by Omarchy
#
# Must be sourced before zsh-syntax-highlighting is loaded
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main cursor)
typeset -gA ZSH_HIGHLIGHT_STYLES

## Comments
ZSH_HIGHLIGHT_STYLES[comment]='fg={{ color8 }}'
## Functions/methods
ZSH_HIGHLIGHT_STYLES[alias]='fg={{ color2 }}'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg={{ color2 }}'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg={{ color2 }}'
ZSH_HIGHLIGHT_STYLES[function]='fg={{ color2 }}'
ZSH_HIGHLIGHT_STYLES[command]='fg={{ color2 }}'
ZSH_HIGHLIGHT_STYLES[precommand]='fg={{ color2 }},italic'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg={{ color3 }},italic'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg={{ color3 }}'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg={{ color3 }}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg={{ color5 }}'
## Built ins
ZSH_HIGHLIGHT_STYLES[builtin]='fg={{ color2 }}'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg={{ color2 }}'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg={{ color2 }}'
## Punctuation
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg={{ color1 }}'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg={{ foreground }}'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]='fg={{ foreground }}'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg={{ foreground }}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg={{ color1 }}'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg={{ color1 }}'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg={{ color1 }}'
## Strings
ZSH_HIGHLIGHT_STYLES[command-substitution-quoted]='fg={{ color3 }}'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-quoted]='fg={{ color3 }}'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg={{ color3 }}'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg={{ color1 }}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg={{ color3 }}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg={{ color1 }}'
ZSH_HIGHLIGHT_STYLES[rc-quote]='fg={{ color3 }}'
## Variables
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg={{ foreground }}'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg={{ color1 }}'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg={{ foreground }}'
ZSH_HIGHLIGHT_STYLES[assign]='fg={{ foreground }}'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg={{ foreground }}'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg={{ foreground }}'
## Misc
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg={{ color1 }}'
ZSH_HIGHLIGHT_STYLES[path]='fg={{ foreground }},underline'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg={{ color1 }},underline'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg={{ foreground }},underline'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg={{ color1 }},underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg={{ foreground }}'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg={{ color5 }}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-unclosed]='fg={{ color1 }}'
ZSH_HIGHLIGHT_STYLES[redirection]='fg={{ foreground }}'
ZSH_HIGHLIGHT_STYLES[arg0]='fg={{ foreground }}'
ZSH_HIGHLIGHT_STYLES[default]='fg={{ foreground }}'
ZSH_HIGHLIGHT_STYLES[cursor]='fg={{ foreground }}'
